// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: swechain/ipfs/v1/query.proto

package types

import (
	context "context"
	fmt "fmt"
	query "github.com/cosmos/cosmos-sdk/types/query"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// QueryParamsRequest is request type for the Query/Params RPC method.
type QueryParamsRequest struct {
}

func (m *QueryParamsRequest) Reset()         { *m = QueryParamsRequest{} }
func (m *QueryParamsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryParamsRequest) ProtoMessage()    {}
func (*QueryParamsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c5a48e9b9e813b6, []int{0}
}
func (m *QueryParamsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsRequest.Merge(m, src)
}
func (m *QueryParamsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsRequest proto.InternalMessageInfo

// QueryParamsResponse is response type for the Query/Params RPC method.
type QueryParamsResponse struct {
	// params holds all the parameters of this module.
	Params Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
}

func (m *QueryParamsResponse) Reset()         { *m = QueryParamsResponse{} }
func (m *QueryParamsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryParamsResponse) ProtoMessage()    {}
func (*QueryParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c5a48e9b9e813b6, []int{1}
}
func (m *QueryParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsResponse.Merge(m, src)
}
func (m *QueryParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsResponse proto.InternalMessageInfo

func (m *QueryParamsResponse) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

type QueryGetCodingTrajRequest struct {
	Index string `protobuf:"bytes,1,opt,name=index,proto3" json:"index,omitempty"`
}

func (m *QueryGetCodingTrajRequest) Reset()         { *m = QueryGetCodingTrajRequest{} }
func (m *QueryGetCodingTrajRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetCodingTrajRequest) ProtoMessage()    {}
func (*QueryGetCodingTrajRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c5a48e9b9e813b6, []int{2}
}
func (m *QueryGetCodingTrajRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetCodingTrajRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetCodingTrajRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetCodingTrajRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetCodingTrajRequest.Merge(m, src)
}
func (m *QueryGetCodingTrajRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetCodingTrajRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetCodingTrajRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetCodingTrajRequest proto.InternalMessageInfo

func (m *QueryGetCodingTrajRequest) GetIndex() string {
	if m != nil {
		return m.Index
	}
	return ""
}

type QueryGetCodingTrajResponse struct {
	CodingTraj CodingTraj `protobuf:"bytes,1,opt,name=codingTraj,proto3" json:"codingTraj"`
}

func (m *QueryGetCodingTrajResponse) Reset()         { *m = QueryGetCodingTrajResponse{} }
func (m *QueryGetCodingTrajResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetCodingTrajResponse) ProtoMessage()    {}
func (*QueryGetCodingTrajResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c5a48e9b9e813b6, []int{3}
}
func (m *QueryGetCodingTrajResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetCodingTrajResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetCodingTrajResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetCodingTrajResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetCodingTrajResponse.Merge(m, src)
}
func (m *QueryGetCodingTrajResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetCodingTrajResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetCodingTrajResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetCodingTrajResponse proto.InternalMessageInfo

func (m *QueryGetCodingTrajResponse) GetCodingTraj() CodingTraj {
	if m != nil {
		return m.CodingTraj
	}
	return CodingTraj{}
}

type QueryAllCodingTrajRequest struct {
	Pagination *query.PageRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllCodingTrajRequest) Reset()         { *m = QueryAllCodingTrajRequest{} }
func (m *QueryAllCodingTrajRequest) String() string { return proto.CompactTextString(m) }
func (*QueryAllCodingTrajRequest) ProtoMessage()    {}
func (*QueryAllCodingTrajRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c5a48e9b9e813b6, []int{4}
}
func (m *QueryAllCodingTrajRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllCodingTrajRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllCodingTrajRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllCodingTrajRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllCodingTrajRequest.Merge(m, src)
}
func (m *QueryAllCodingTrajRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllCodingTrajRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllCodingTrajRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllCodingTrajRequest proto.InternalMessageInfo

func (m *QueryAllCodingTrajRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryAllCodingTrajResponse struct {
	CodingTraj []CodingTraj        `protobuf:"bytes,1,rep,name=codingTraj,proto3" json:"codingTraj"`
	Pagination *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllCodingTrajResponse) Reset()         { *m = QueryAllCodingTrajResponse{} }
func (m *QueryAllCodingTrajResponse) String() string { return proto.CompactTextString(m) }
func (*QueryAllCodingTrajResponse) ProtoMessage()    {}
func (*QueryAllCodingTrajResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c5a48e9b9e813b6, []int{5}
}
func (m *QueryAllCodingTrajResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllCodingTrajResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllCodingTrajResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllCodingTrajResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllCodingTrajResponse.Merge(m, src)
}
func (m *QueryAllCodingTrajResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllCodingTrajResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllCodingTrajResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllCodingTrajResponse proto.InternalMessageInfo

func (m *QueryAllCodingTrajResponse) GetCodingTraj() []CodingTraj {
	if m != nil {
		return m.CodingTraj
	}
	return nil
}

func (m *QueryAllCodingTrajResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

func init() {
	proto.RegisterType((*QueryParamsRequest)(nil), "swechain.ipfs.v1.QueryParamsRequest")
	proto.RegisterType((*QueryParamsResponse)(nil), "swechain.ipfs.v1.QueryParamsResponse")
	proto.RegisterType((*QueryGetCodingTrajRequest)(nil), "swechain.ipfs.v1.QueryGetCodingTrajRequest")
	proto.RegisterType((*QueryGetCodingTrajResponse)(nil), "swechain.ipfs.v1.QueryGetCodingTrajResponse")
	proto.RegisterType((*QueryAllCodingTrajRequest)(nil), "swechain.ipfs.v1.QueryAllCodingTrajRequest")
	proto.RegisterType((*QueryAllCodingTrajResponse)(nil), "swechain.ipfs.v1.QueryAllCodingTrajResponse")
}

func init() { proto.RegisterFile("swechain/ipfs/v1/query.proto", fileDescriptor_4c5a48e9b9e813b6) }

var fileDescriptor_4c5a48e9b9e813b6 = []byte{
	// 530 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x94, 0x41, 0x6f, 0xd3, 0x30,
	0x14, 0xc7, 0xeb, 0x8d, 0x55, 0x9a, 0x11, 0x08, 0x4c, 0x0f, 0xa3, 0x2a, 0x01, 0x05, 0xca, 0xd0,
	0xca, 0x6c, 0x65, 0x88, 0x13, 0x27, 0x8a, 0x60, 0x17, 0x0e, 0x23, 0xe2, 0xc4, 0x05, 0xdc, 0xcc,
	0xa4, 0x9e, 0x1a, 0x3b, 0x8b, 0xdd, 0xb2, 0x09, 0x71, 0xd9, 0x27, 0x40, 0xe2, 0xc6, 0x8d, 0x1b,
	0xdc, 0xf8, 0x18, 0xbb, 0x20, 0x4d, 0xe2, 0xc2, 0x09, 0xa1, 0x16, 0x89, 0xaf, 0x81, 0x62, 0x7b,
	0xac, 0x5d, 0x12, 0xad, 0x5c, 0x22, 0xc7, 0xef, 0xfd, 0xdf, 0xff, 0x67, 0xbf, 0x97, 0xc0, 0x96,
	0x7a, 0xc3, 0xa2, 0x3e, 0xe5, 0x82, 0xf0, 0xf4, 0xb5, 0x22, 0xa3, 0x80, 0xec, 0x0e, 0x59, 0xb6,
	0x8f, 0xd3, 0x4c, 0x6a, 0x89, 0x2e, 0x1d, 0x47, 0x71, 0x1e, 0xc5, 0xa3, 0xa0, 0x79, 0x99, 0x26,
	0x5c, 0x48, 0x62, 0x9e, 0x36, 0xa9, 0xd9, 0x88, 0x65, 0x2c, 0xcd, 0x92, 0xe4, 0x2b, 0xb7, 0xdb,
	0x8a, 0xa5, 0x8c, 0x07, 0x8c, 0xd0, 0x94, 0x13, 0x2a, 0x84, 0xd4, 0x54, 0x73, 0x29, 0x94, 0x8b,
	0xae, 0x45, 0x52, 0x25, 0x52, 0x91, 0x1e, 0x55, 0xcc, 0x3a, 0x92, 0x51, 0xd0, 0x63, 0x9a, 0x06,
	0x24, 0xa5, 0x31, 0x17, 0x26, 0xd9, 0xe5, 0x5e, 0x2b, 0x20, 0xa6, 0x34, 0xa3, 0xc9, 0x71, 0x29,
	0xbf, 0x10, 0x8e, 0xe4, 0x36, 0x17, 0xf1, 0x4b, 0x9d, 0xd1, 0x1d, 0x9b, 0xe3, 0x37, 0x20, 0x7a,
	0x96, 0x9b, 0x6c, 0x19, 0x61, 0xc8, 0x76, 0x87, 0x4c, 0x69, 0x3f, 0x84, 0x57, 0x66, 0x76, 0x55,
	0x2a, 0x85, 0x62, 0xe8, 0x01, 0xac, 0x5b, 0x83, 0x15, 0x70, 0x03, 0xdc, 0x39, 0xbf, 0xb1, 0x82,
	0x4f, 0xdf, 0x02, 0xb6, 0x8a, 0xee, 0xf2, 0xe1, 0xcf, 0xeb, 0xb5, 0xcf, 0x7f, 0xbe, 0xae, 0x81,
	0xd0, 0x49, 0xfc, 0x00, 0x5e, 0x35, 0x35, 0x37, 0x99, 0x7e, 0x64, 0x30, 0x9e, 0x67, 0x74, 0xc7,
	0x19, 0xa2, 0x06, 0x5c, 0xe2, 0x62, 0x9b, 0xed, 0x99, 0xc2, 0xcb, 0xa1, 0x7d, 0xf1, 0x5f, 0xc1,
	0x66, 0x99, 0xc4, 0xd1, 0x74, 0x21, 0x8c, 0xfe, 0xed, 0x3a, 0xa2, 0x56, 0x91, 0xe8, 0x44, 0xd9,
	0x3d, 0x97, 0x53, 0x85, 0x53, 0x2a, 0x3f, 0x72, 0x50, 0x0f, 0x07, 0x83, 0x22, 0xd4, 0x13, 0x08,
	0x4f, 0xae, 0xdc, 0x19, 0xdc, 0xc6, 0xb6, 0x3f, 0x38, 0xef, 0x0f, 0xb6, 0x13, 0xe1, 0xfa, 0x83,
	0xb7, 0x68, 0xcc, 0x9c, 0x36, 0x9c, 0x52, 0xfa, 0x5f, 0x80, 0x3b, 0xc7, 0x29, 0x97, 0x8a, 0x73,
	0x2c, 0xfe, 0xff, 0x39, 0xd0, 0xe6, 0x0c, 0xea, 0x82, 0x41, 0x5d, 0x3d, 0x13, 0xd5, 0x02, 0x4c,
	0xb3, 0x6e, 0x7c, 0x5b, 0x84, 0x4b, 0x86, 0x15, 0x1d, 0x00, 0x58, 0xb7, 0xdd, 0x44, 0xb7, 0x8a,
	0x34, 0xc5, 0xa1, 0x69, 0xb6, 0xcf, 0xc8, 0xb2, 0x6e, 0x7e, 0xe7, 0xe0, 0xfb, 0xef, 0x0f, 0x0b,
	0x6d, 0x74, 0x93, 0x24, 0x32, 0x63, 0x8a, 0xd1, 0x2c, 0xea, 0x93, 0x8a, 0x41, 0x46, 0x9f, 0x00,
	0xbc, 0x30, 0xd3, 0x7d, 0xd4, 0xa9, 0x70, 0x29, 0x1b, 0xab, 0xe6, 0xdd, 0xf9, 0x92, 0x1d, 0xd9,
	0x7d, 0x43, 0x46, 0xd0, 0x7a, 0x35, 0xd9, 0xd4, 0x07, 0x44, 0xde, 0x9a, 0x21, 0x7d, 0x87, 0x3e,
	0x02, 0x78, 0xf1, 0x29, 0x57, 0xf3, 0x40, 0x96, 0x8d, 0x59, 0x25, 0x64, 0xe9, 0xb4, 0xf8, 0xeb,
	0x06, 0x72, 0x15, 0xb5, 0xe7, 0x82, 0xec, 0x3e, 0x3e, 0x1c, 0x7b, 0xe0, 0x68, 0xec, 0x81, 0x5f,
	0x63, 0x0f, 0xbc, 0x9f, 0x78, 0xb5, 0xa3, 0x89, 0x57, 0xfb, 0x31, 0xf1, 0x6a, 0x2f, 0x3a, 0x31,
	0xd7, 0xfd, 0x61, 0x0f, 0x47, 0x32, 0x29, 0x2d, 0xb5, 0x67, 0x8b, 0xe9, 0xfd, 0x94, 0xa9, 0x5e,
	0xdd, 0xfc, 0x2d, 0xee, 0xfd, 0x0d, 0x00, 0x00, 0xff, 0xff, 0x4b, 0x9b, 0xb6, 0x05, 0x15, 0x05,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// Parameters queries the parameters of the module.
	Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
	// Queries a list of CodingTraj items.
	GetCodingTraj(ctx context.Context, in *QueryGetCodingTrajRequest, opts ...grpc.CallOption) (*QueryGetCodingTrajResponse, error)
	ListCodingTraj(ctx context.Context, in *QueryAllCodingTrajRequest, opts ...grpc.CallOption) (*QueryAllCodingTrajResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, "/swechain.ipfs.v1.Query/Params", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) GetCodingTraj(ctx context.Context, in *QueryGetCodingTrajRequest, opts ...grpc.CallOption) (*QueryGetCodingTrajResponse, error) {
	out := new(QueryGetCodingTrajResponse)
	err := c.cc.Invoke(ctx, "/swechain.ipfs.v1.Query/GetCodingTraj", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) ListCodingTraj(ctx context.Context, in *QueryAllCodingTrajRequest, opts ...grpc.CallOption) (*QueryAllCodingTrajResponse, error) {
	out := new(QueryAllCodingTrajResponse)
	err := c.cc.Invoke(ctx, "/swechain.ipfs.v1.Query/ListCodingTraj", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// Parameters queries the parameters of the module.
	Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
	// Queries a list of CodingTraj items.
	GetCodingTraj(context.Context, *QueryGetCodingTrajRequest) (*QueryGetCodingTrajResponse, error)
	ListCodingTraj(context.Context, *QueryAllCodingTrajRequest) (*QueryAllCodingTrajResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Params(ctx context.Context, req *QueryParamsRequest) (*QueryParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Params not implemented")
}
func (*UnimplementedQueryServer) GetCodingTraj(ctx context.Context, req *QueryGetCodingTrajRequest) (*QueryGetCodingTrajResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCodingTraj not implemented")
}
func (*UnimplementedQueryServer) ListCodingTraj(ctx context.Context, req *QueryAllCodingTrajRequest) (*QueryAllCodingTrajResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListCodingTraj not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/swechain.ipfs.v1.Query/Params",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Params(ctx, req.(*QueryParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_GetCodingTraj_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetCodingTrajRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).GetCodingTraj(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/swechain.ipfs.v1.Query/GetCodingTraj",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).GetCodingTraj(ctx, req.(*QueryGetCodingTrajRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_ListCodingTraj_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAllCodingTrajRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).ListCodingTraj(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/swechain.ipfs.v1.Query/ListCodingTraj",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).ListCodingTraj(ctx, req.(*QueryAllCodingTrajRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var Query_serviceDesc = _Query_serviceDesc
var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "swechain.ipfs.v1.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
		{
			MethodName: "GetCodingTraj",
			Handler:    _Query_GetCodingTraj_Handler,
		},
		{
			MethodName: "ListCodingTraj",
			Handler:    _Query_ListCodingTraj_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "swechain/ipfs/v1/query.proto",
}

func (m *QueryParamsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryGetCodingTrajRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetCodingTrajRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetCodingTrajRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Index) > 0 {
		i -= len(m.Index)
		copy(dAtA[i:], m.Index)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Index)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetCodingTrajResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetCodingTrajResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetCodingTrajResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.CodingTraj.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryAllCodingTrajRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllCodingTrajRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllCodingTrajRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryAllCodingTrajResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllCodingTrajResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllCodingTrajResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.CodingTraj) > 0 {
		for iNdEx := len(m.CodingTraj) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.CodingTraj[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryParamsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryGetCodingTrajRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Index)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetCodingTrajResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.CodingTraj.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryAllCodingTrajRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryAllCodingTrajResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.CodingTraj) > 0 {
		for _, e := range m.CodingTraj {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryParamsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetCodingTrajRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetCodingTrajRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetCodingTrajRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Index", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Index = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetCodingTrajResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetCodingTrajResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetCodingTrajResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CodingTraj", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.CodingTraj.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllCodingTrajRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllCodingTrajRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllCodingTrajRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllCodingTrajResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllCodingTrajResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllCodingTrajResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CodingTraj", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CodingTraj = append(m.CodingTraj, CodingTraj{})
			if err := m.CodingTraj[len(m.CodingTraj)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
